site_name: FastAPI project

nav:
  - About: index.md
  - Examples: examples.md

theme:
  name: material
  features:
    - navigation.tabs
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate

# for syntax highlighting
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
